development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: pitchhub_development
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:
    secret_keeper_1:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10469,candidate.54.mongolayer.com:10208/secret_keeper?replicaSet=set-56171549608aa66e490006a4
      options:
    secret_keeper_2:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10470,candidate.54.mongolayer.com:10209/secret_keeper?replicaSet=set-56171560147ca745d800040e
      options:
    secret_keeper_3:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10471,candidate.54.mongolayer.com:10210/secret_keeper?replicaSet=set-56171574d893a2ccf9000633
      options:
    secret_keeper_4:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10472,candidate.54.mongolayer.com:10211/secret_keeper?replicaSet=set-561715a730354b363c000778
      options:

  # Configure Mongoid specific options. (optional)
  options:
test:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: pitchhub_test
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:
    secret_keeper_1:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10469,candidate.54.mongolayer.com:10208/secret_keeper?replicaSet=set-56171549608aa66e490006a4
      options:
    secret_keeper_2:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10470,candidate.54.mongolayer.com:10209/secret_keeper?replicaSet=set-56171560147ca745d800040e
      options:
    secret_keeper_3:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10471,candidate.54.mongolayer.com:10210/secret_keeper?replicaSet=set-56171574d893a2ccf9000633
      options:
    secret_keeper_4:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10472,candidate.54.mongolayer.com:10211/secret_keeper?replicaSet=set-561715a730354b363c000778
      options:

  # Configure Mongoid specific options. (optional)
  options:
#test:
#  sessions:
#    default:
#      database: pitchhub_test
#      hosts:
#        - localhost:27017
#      options:
#        read: primary
#        # In the test environment we lower the retries and retry interval to
#        # low amounts for fast failures.
#        max_retries: 1
#        retry_interval: 0

production:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: pitchhub_production
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:
    secret_keeper_1:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10469,candidate.54.mongolayer.com:10208/secret_keeper?replicaSet=set-56171549608aa66e490006a4
      options:
    secret_keeper_2:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10470,candidate.54.mongolayer.com:10209/secret_keeper?replicaSet=set-56171560147ca745d800040e
      options:
    secret_keeper_3:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10471,candidate.54.mongolayer.com:10210/secret_keeper?replicaSet=set-56171574d893a2ccf9000633
      options:
    secret_keeper_4:
      uri: mongodb://michael:Composed.fireball.27@candidate.53.mongolayer.com:10472,candidate.54.mongolayer.com:10211/secret_keeper?replicaSet=set-561715a730354b363c000778
      options:
