# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>
  email_provider_username: <%= ENV["EMAIL_USERNAME_DEVELOPMENT"] %>
  email_provider_password: <%= ENV["EMAIL_PASSWORD_DEVELOPMENT"] %>
  domain_name: <%= ENV["DOMAIN_NAME_LOCAL"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>
  email_provider_username: <%= ENV["EMAIL_USERNAME_TEST"] %>
  email_provider_password: <%= ENV["EMAIL_PASSWORD_TEST"] %>
  domain_name: <%= ENV["DOMAIN_NAME_LOCAL"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PRODUCTION"] %>
  email_provider_username: <%= ENV["EMAIL_USERNAME_PRODUCTION"] %>
  email_provider_password: <%= ENV["EMAIL_PASSWORD_PRODUCTION"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
